<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'bbeec56141e5d15e97853b9831244f18',
  'DATABASE_URL' => 'mysql://root@127.0.0.1:3306/meetntrip3',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
  'STRIPE_SECRET_KEY' => 'sk_test_51Qwrrl4gBlnREYNzxG7WoyH1b3kYBMGx992KASpDQHj0jPJBtECuTxqGTvuDyTd9S9p75l9Pr7eR7WX40NEHAClY00nbIXdJuX',
);
