<?php

namespace Proxies\__CG__\App\Entity\gestion_user;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\gestion_user\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bookings' => [parent::class, 'bookings', null, 16],
        "\0".parent::class."\0".'compteValide' => [parent::class, 'compteValide', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'evenements' => [parent::class, 'evenements', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'motDePasse' => [parent::class, 'motDePasse', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'bookings' => [parent::class, 'bookings', null, 16],
        'compteValide' => [parent::class, 'compteValide', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'evenements' => [parent::class, 'evenements', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'motDePasse' => [parent::class, 'motDePasse', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
