<?php

namespace Proxies\__CG__\App\Entity\Gestion_Evenement;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Gestion_Evenement\Evenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activities' => [parent::class, 'activities', null, 16],
        "\0".parent::class."\0".'budgetPrevu' => [parent::class, 'budgetPrevu', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'demandesSponsoring' => [parent::class, 'demandesSponsoring', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'eventMood' => [parent::class, 'eventMood', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imagePath' => [parent::class, 'imagePath', null, 16],
        "\0".parent::class."\0".'lieuEvenement' => [parent::class, 'lieuEvenement', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'nombreInvite' => [parent::class, 'nombreInvite', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'validated' => [parent::class, 'validated', null, 16],
        'activities' => [parent::class, 'activities', null, 16],
        'budgetPrevu' => [parent::class, 'budgetPrevu', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'demandesSponsoring' => [parent::class, 'demandesSponsoring', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'eventMood' => [parent::class, 'eventMood', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imagePath' => [parent::class, 'imagePath', null, 16],
        'lieuEvenement' => [parent::class, 'lieuEvenement', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'nombreInvite' => [parent::class, 'nombreInvite', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'validated' => [parent::class, 'validated', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
