<?php

namespace Proxies\__CG__\App\Entity\gestion_de_reservation;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \App\Entity\gestion_de_reservation\Hotel implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'hotelId' => [parent::class, 'hotelId', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'pricePerNight' => [parent::class, 'pricePerNight', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'hotelId' => [parent::class, 'hotelId', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'pricePerNight' => [parent::class, 'pricePerNight', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
