<?php

namespace Proxies\__CG__\App\Entity\gestion_de_reservation;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Flight extends \App\Entity\gestion_de_reservation\Flight implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aeroports' => [parent::class, 'aeroports', null, 16],
        "\0".parent::class."\0".'airline' => [parent::class, 'airline', null, 16],
        "\0".parent::class."\0".'backTime' => [parent::class, 'backTime', null, 16],
        "\0".parent::class."\0".'departureTime' => [parent::class, 'departureTime', null, 16],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null, 16],
        "\0".parent::class."\0".'flightId' => [parent::class, 'flightId', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'aeroports' => [parent::class, 'aeroports', null, 16],
        'airline' => [parent::class, 'airline', null, 16],
        'backTime' => [parent::class, 'backTime', null, 16],
        'departureTime' => [parent::class, 'departureTime', null, 16],
        'destination' => [parent::class, 'destination', null, 16],
        'flightId' => [parent::class, 'flightId', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
