<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBUBScs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBUBScs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBUBScs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBUBScs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBUBScs\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBUBScs',
    'container.build_id' => '2ea75c52',
    'container.build_time' => 1744918961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBUBScs');
