<?php

namespace ContainerXBUBScs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_08Pc_B7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.08Pc.B7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.08Pc.B7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transportRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\TransportRepository', 'getTransportRepositoryService', true],
        ], [
            'entityManager' => '?',
            'transportRepository' => 'App\\Repository\\gestion_de_reservation\\TransportRepository',
        ]);
    }
}
