<?php

namespace ContainerXBUBScs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CNH59jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cNH_59j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cNH_59j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.cNH_59j.App\\Entity\\Gestion_Evenement\\Evenement', NULL, 'Cannot autowire service ".service_locator.cNH_59j": it references class "App\\Entity\\Gestion_Evenement\\Evenement" but no such service exists.'],
        ], [
            'evenement' => 'App\\Entity\\Gestion_Evenement\\Evenement',
        ]);
    }
}
