<?php

namespace ContainerXBUBScs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PVpiX9PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PVpiX9P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PVpiX9P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\Gestion_evenement\\DemandeSponsoringRepository', 'getDemandeSponsoringRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\Gestion_evenement\\DemandeSponsoringRepository',
        ]);
    }
}
