<?php

namespace ContainerXBUBScs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cNH_59j.App\Entity\Gestion_Evenement\Evenement' shared service.
     *
     * @return \App\Entity\Gestion_Evenement\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cNH_59j": it references class "App\\Entity\\Gestion_Evenement\\Evenement" but no such service exists.');
    }
}
