<?php

namespace ContainerXBUBScs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\gestion_de_reservation\TransportController' shared autowired service.
     *
     * @return \App\Controller\gestion_de_reservation\TransportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'gestion_de_reservation'.\DIRECTORY_SEPARATOR.'TransportController.php';

        $container->services['App\\Controller\\gestion_de_reservation\\TransportController'] = $instance = new \App\Controller\gestion_de_reservation\TransportController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\gestion_de_reservation\\TransportController', $container));

        return $instance;
    }
}
