<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__OtRfHqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..otRfHq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..otRfHq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookingRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\BookingRepository', 'getBookingRepositoryService', true],
        ], [
            'bookingRepository' => 'App\\Repository\\gestion_de_reservation\\BookingRepository',
        ]);
    }
}
