<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVCimojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qVCimoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qVCimoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conferenceLocationRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\ConferenceLocationRepository', 'getConferenceLocationRepositoryService', true],
            'evenementRepository' => ['privates', 'App\\Repository\\Gestion_evenement\\EvenementRepository', 'getEvenementRepositoryService', true],
            'flightRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\FlightRepository', 'getFlightRepositoryService', true],
            'hotelRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\HotelRepository', 'getHotelRepositoryService', true],
            'transportRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\TransportRepository', 'getTransportRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\gestion_user\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'conferenceLocationRepository' => 'App\\Repository\\gestion_de_reservation\\ConferenceLocationRepository',
            'evenementRepository' => 'App\\Repository\\Gestion_evenement\\EvenementRepository',
            'flightRepository' => 'App\\Repository\\gestion_de_reservation\\FlightRepository',
            'hotelRepository' => 'App\\Repository\\gestion_de_reservation\\HotelRepository',
            'transportRepository' => 'App\\Repository\\gestion_de_reservation\\TransportRepository',
            'userRepository' => 'App\\Repository\\gestion_user\\UserRepository',
        ]);
    }
}
