<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NsJjqgJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nsJjqgJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nsJjqgJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.nsJjqgJ.Symfony\\Component\\Security\\Http\\Event\\InteractiveLoginEvent', NULL, 'Cannot autowire service ".service_locator.nsJjqgJ": it references class "Symfony\\Component\\Security\\Http\\Event\\InteractiveLoginEvent" but no such service exists.'],
        ], [
            'event' => 'Symfony\\Component\\Security\\Http\\Event\\InteractiveLoginEvent',
        ]);
    }
}
