<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qi8VovKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qi8VovK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qi8VovK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenementRepository' => ['privates', 'App\\Repository\\Gestion_evenement\\EvenementRepository', 'getEvenementRepositoryService', true],
            'flightRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\FlightRepository', 'getFlightRepositoryService', true],
        ], [
            'evenementRepository' => 'App\\Repository\\Gestion_evenement\\EvenementRepository',
            'flightRepository' => 'App\\Repository\\gestion_de_reservation\\FlightRepository',
        ]);
    }
}
