<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SEFKkeiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SEFKkei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SEFKkei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transportRepository' => ['privates', 'App\\Repository\\gestion_de_reservation\\TransportRepository', 'getTransportRepositoryService', true],
        ], [
            'transportRepository' => 'App\\Repository\\gestion_de_reservation\\TransportRepository',
        ]);
    }
}
