<?php

namespace ContainerZctXMLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eLcYg_6.App\Entity\gestion_user\User' shared service.
     *
     * @return \App\Entity\gestion_user\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eLcYg_6": it references class "App\\Entity\\gestion_user\\User" but no such service exists.');
    }
}
